### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [jsreport/jsreport-postgres-store#1]
``` js
var pg = require('pg-promise')({promise: q})
```

The parameter name is [promiseLib](https://github.com/vitaly-t/pg-promise#promiselib), not `promise` ;)

**Comment by pofider** [comment]
That was fast. Thank you!

**Comment by vitaly-t** [comment]
n.p.

**Comment by vitaly-t** [comment]
```js
   for (var i = 0; i < q.values.length; i++) {
      if (Buffer.isBuffer(q.values[i])) {
        q.values[i] = '\\x' + q.values[i].toString('hex')
      }
    }
````
- pg-promise knows how to format `Buffer` objects automatically, there is no need for such a conversion.

**Comment by vitaly-t** [comment]
@pofider 

why are you doing this? - 
```js
 for (var i = 0; i < q.values.length; i++) {
      if (Buffer.isBuffer(q.values[i])) {
        q.values[i] = '\\x' + q.values[i].toString('hex')
      }
    }
```
pg-promise converts object Buffer into a proper string automatically.

**Comment by pofider** [comment]
@vitaly-t Ok, I've now task to try it without it - https://github.com/jsreport/jsreport-postgres-store/issues/2
Thank you
