### ISSUE TITLE
Configure variables from ENV

### ISSUE THREAD

**Issue by dev-on2air** [jsreport/jsreport-postgres-store#6]
I have my database settings stored within the environment. Is there a way to retrieve those to use within this extension to avoid saving in the config file?  i.e - if the json file were a js file, I could use process.env.DATABASE

**Comment by bjrmatos** [comment]
hi! jsreport can be configured also from env vars, see [here](https://jsreport.net/learn/configuration#environment-variables)

to configure some postgres-store configuration, an example env var would look like this:

```
extensions_postgres_store_host=localhost
```

you just need to set it when starting your app, in any way you like
