### ISSUE TITLE
Support for SSL

### ISSUE THREAD

**Issue by dev-on2air** [jsreport/jsreport-postgres-store#7]
our postgres database requires SSL connection. This is typically a setting that requires referencing a ca certificate file in order to connect.  Is it possible to connect with those settings?

**Comment by bjrmatos** [comment]
I see there are some [SSL options in the pg client we use](https://node-postgres.com/features/ssl), however, I see they need the content of the ca file, not just the path, in that case, it is supported if you specify the ca content.

when using env vars it will look like this

```
extensions_postgres_store_ssl_ca=<raw content of file here>
extensions_postgres_store_ssl_key=<raw content of file here>
extensions_postgres_store_ssl_cert=<raw content of file here>
```

**Comment by ekoputrapratama** [comment]
i got the same error like this in heroku cuz it need to use SSL but i don't have the ca file, can you please fix it ? or maybe create a new store but using firebase realtime database/firestore

**Comment by pofider** [comment]
When you don't need to select a certificate file, you can just enable SSL by setting `extensions_postgres_store_ssl=true`
Or in the config file

```js
"extensions": {
		"postgres-store": {
			"host": "localhost",
			"port": 5432,
			"database": "jsreport",
			"user": "postgres",
			"password": "password",			
			"ssl": true
               }
}
```

**Comment by ekoputrapratama** [comment]
when i add that option i got this error
`Error: self signed certificate in certificate chain`

**Comment by pofider** [comment]
This would mean the server uses a self-signed certificate and you really need to pass the ca as described here https://node-postgres.com/features/ssl
I tried the `ssl:true` with azure Postgres database having a proper certificate and I had no issues. Didn't have to specify the ca.
